/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApoyoFamiliarRouteImport } from './routes/apoyo-familiar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoyoFamiliarStateRouteImport } from './routes/apoyo-familiar.$state'

const ApoyoFamiliarRoute = ApoyoFamiliarRouteImport.update({
  id: '/apoyo-familiar',
  path: '/apoyo-familiar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoFamiliarStateRoute = ApoyoFamiliarStateRouteImport.update({
  id: '/$state',
  path: '/$state',
  getParentRoute: () => ApoyoFamiliarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoyo-familiar': typeof ApoyoFamiliarRouteWithChildren
  '/apoyo-familiar/$state': typeof ApoyoFamiliarStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoyo-familiar': typeof ApoyoFamiliarRouteWithChildren
  '/apoyo-familiar/$state': typeof ApoyoFamiliarStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoyo-familiar': typeof ApoyoFamiliarRouteWithChildren
  '/apoyo-familiar/$state': typeof ApoyoFamiliarStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apoyo-familiar' | '/apoyo-familiar/$state'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apoyo-familiar' | '/apoyo-familiar/$state'
  id: '__root__' | '/' | '/apoyo-familiar' | '/apoyo-familiar/$state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoyoFamiliarRoute: typeof ApoyoFamiliarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apoyo-familiar': {
      id: '/apoyo-familiar'
      path: '/apoyo-familiar'
      fullPath: '/apoyo-familiar'
      preLoaderRoute: typeof ApoyoFamiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo-familiar/$state': {
      id: '/apoyo-familiar/$state'
      path: '/$state'
      fullPath: '/apoyo-familiar/$state'
      preLoaderRoute: typeof ApoyoFamiliarStateRouteImport
      parentRoute: typeof ApoyoFamiliarRoute
    }
  }
}

interface ApoyoFamiliarRouteChildren {
  ApoyoFamiliarStateRoute: typeof ApoyoFamiliarStateRoute
}

const ApoyoFamiliarRouteChildren: ApoyoFamiliarRouteChildren = {
  ApoyoFamiliarStateRoute: ApoyoFamiliarStateRoute,
}

const ApoyoFamiliarRouteWithChildren = ApoyoFamiliarRoute._addFileChildren(
  ApoyoFamiliarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoyoFamiliarRoute: ApoyoFamiliarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
