/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as TerminosSmsRouteImport } from './routes/terminos-sms'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RespuestasFamiliaRouteImport } from './routes/respuestas-familia'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PaisesRouteImport } from './routes/paises'
import { Route as MembresiaRouteImport } from './routes/membresia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IntervencionRouteImport } from './routes/intervencion'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as HerramientasIaRouteImport } from './routes/herramientas-ia'
import { Route as GrabacionesRouteImport } from './routes/grabaciones'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EvaluacionesRouteImport } from './routes/evaluaciones'
import { Route as CoachingPagoRouteImport } from './routes/coaching-pago'
import { Route as CoachingFamiliarRouteImport } from './routes/coaching-familiar'
import { Route as CirculoFamiliarRouteImport } from './routes/circulo-familiar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApoyoFamiliarRouteImport } from './routes/apoyo-familiar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RespuestasFamiliaIndexRouteImport } from './routes/respuestas-familia.index'
import { Route as RecursosIndexRouteImport } from './routes/recursos.index'
import { Route as PaisesIndexRouteImport } from './routes/paises.index'
import { Route as MembresiaIndexRouteImport } from './routes/membresia.index'
import { Route as MapaIndexRouteImport } from './routes/mapa.index'
import { Route as HerramientasIaIndexRouteImport } from './routes/herramientas-ia.index'
import { Route as CoachingPagoIndexRouteImport } from './routes/coaching-pago.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ApoyoFamiliarIndexRouteImport } from './routes/apoyo-familiar.index'
import { Route as RespuestasFamiliaSlugRouteImport } from './routes/respuestas-familia.$slug'
import { Route as RecursosSlugRouteImport } from './routes/recursos.$slug'
import { Route as PaisesCountryRouteImport } from './routes/paises.$country'
import { Route as MembresiaExitoRouteImport } from './routes/membresia.exito'
import { Route as MembresiaCanceladoRouteImport } from './routes/membresia.cancelado'
import { Route as MapaSlugRouteImport } from './routes/mapa.$slug'
import { Route as HerramientasIaSlugRouteImport } from './routes/herramientas-ia.$slug'
import { Route as CoachingPagoExitoRouteImport } from './routes/coaching-pago.exito'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApoyoFamiliarStateRouteImport } from './routes/apoyo-familiar.$state'
import { Route as ApiRegistroRouteImport } from './routes/api.registro'
import { Route as ApoyoFamiliarStateIndexRouteImport } from './routes/apoyo-familiar.$state.index'
import { Route as ApoyoFamiliarStateCityRouteImport } from './routes/apoyo-familiar.$state.$city'
import { Route as ApiZoomWebhookRouteImport } from './routes/api.zoom.webhook'
import { Route as ApiZoomScheduleRouteImport } from './routes/api.zoom.schedule'
import { Route as ApiZoomRegisterRouteImport } from './routes/api.zoom.register'
import { Route as ApiZoomAutomationRouteImport } from './routes/api.zoom.automation'

const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosSmsRoute = TerminosSmsRouteImport.update({
  id: '/terminos-sms',
  path: '/terminos-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RespuestasFamiliaRoute = RespuestasFamiliaRouteImport.update({
  id: '/respuestas-familia',
  path: '/respuestas-familia',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesRoute = PaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresiaRoute = MembresiaRouteImport.update({
  id: '/membresia',
  path: '/membresia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervencionRoute = IntervencionRouteImport.update({
  id: '/intervencion',
  path: '/intervencion',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasIaRoute = HerramientasIaRouteImport.update({
  id: '/herramientas-ia',
  path: '/herramientas-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const GrabacionesRoute = GrabacionesRouteImport.update({
  id: '/grabaciones',
  path: '/grabaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesRoute = EvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingPagoRoute = CoachingPagoRouteImport.update({
  id: '/coaching-pago',
  path: '/coaching-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingFamiliarRoute = CoachingFamiliarRouteImport.update({
  id: '/coaching-familiar',
  path: '/coaching-familiar',
  getParentRoute: () => rootRouteImport,
} as any)
const CirculoFamiliarRoute = CirculoFamiliarRouteImport.update({
  id: '/circulo-familiar',
  path: '/circulo-familiar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoFamiliarRoute = ApoyoFamiliarRouteImport.update({
  id: '/apoyo-familiar',
  path: '/apoyo-familiar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RespuestasFamiliaIndexRoute = RespuestasFamiliaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RespuestasFamiliaRoute,
} as any)
const RecursosIndexRoute = RecursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecursosRoute,
} as any)
const PaisesIndexRoute = PaisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaisesRoute,
} as any)
const MembresiaIndexRoute = MembresiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembresiaRoute,
} as any)
const MapaIndexRoute = MapaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapaRoute,
} as any)
const HerramientasIaIndexRoute = HerramientasIaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HerramientasIaRoute,
} as any)
const CoachingPagoIndexRoute = CoachingPagoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachingPagoRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ApoyoFamiliarIndexRoute = ApoyoFamiliarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApoyoFamiliarRoute,
} as any)
const RespuestasFamiliaSlugRoute = RespuestasFamiliaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RespuestasFamiliaRoute,
} as any)
const RecursosSlugRoute = RecursosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecursosRoute,
} as any)
const PaisesCountryRoute = PaisesCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => PaisesRoute,
} as any)
const MembresiaExitoRoute = MembresiaExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => MembresiaRoute,
} as any)
const MembresiaCanceladoRoute = MembresiaCanceladoRouteImport.update({
  id: '/cancelado',
  path: '/cancelado',
  getParentRoute: () => MembresiaRoute,
} as any)
const MapaSlugRoute = MapaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MapaRoute,
} as any)
const HerramientasIaSlugRoute = HerramientasIaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HerramientasIaRoute,
} as any)
const CoachingPagoExitoRoute = CoachingPagoExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => CoachingPagoRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApoyoFamiliarStateRoute = ApoyoFamiliarStateRouteImport.update({
  id: '/$state',
  path: '/$state',
  getParentRoute: () => ApoyoFamiliarRoute,
} as any)
const ApiRegistroRoute = ApiRegistroRouteImport.update({
  id: '/api/registro',
  path: '/api/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoFamiliarStateIndexRoute = ApoyoFamiliarStateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApoyoFamiliarStateRoute,
} as any)
const ApoyoFamiliarStateCityRoute = ApoyoFamiliarStateCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ApoyoFamiliarStateRoute,
} as any)
const ApiZoomWebhookRoute = ApiZoomWebhookRouteImport.update({
  id: '/api/zoom/webhook',
  path: '/api/zoom/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZoomScheduleRoute = ApiZoomScheduleRouteImport.update({
  id: '/api/zoom/schedule',
  path: '/api/zoom/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZoomRegisterRoute = ApiZoomRegisterRouteImport.update({
  id: '/api/zoom/register',
  path: '/api/zoom/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZoomAutomationRoute = ApiZoomAutomationRouteImport.update({
  id: '/api/zoom/automation',
  path: '/api/zoom/automation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apoyo-familiar': typeof ApoyoFamiliarRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/circulo-familiar': typeof CirculoFamiliarRoute
  '/coaching-familiar': typeof CoachingFamiliarRoute
  '/coaching-pago': typeof CoachingPagoRouteWithChildren
  '/evaluaciones': typeof EvaluacionesRoute
  '/faq': typeof FaqRoute
  '/grabaciones': typeof GrabacionesRoute
  '/herramientas-ia': typeof HerramientasIaRouteWithChildren
  '/ingresar': typeof IngresarRoute
  '/intervencion': typeof IntervencionRoute
  '/mapa': typeof MapaRouteWithChildren
  '/membresia': typeof MembresiaRouteWithChildren
  '/paises': typeof PaisesRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/proveedores': typeof ProveedoresRoute
  '/recursos': typeof RecursosRouteWithChildren
  '/registro': typeof RegistroRoute
  '/respuestas-familia': typeof RespuestasFamiliaRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/terminos-sms': typeof TerminosSmsRoute
  '/testimonios': typeof TestimoniosRoute
  '/api/registro': typeof ApiRegistroRoute
  '/apoyo-familiar/$state': typeof ApoyoFamiliarStateRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/coaching-pago/exito': typeof CoachingPagoExitoRoute
  '/herramientas-ia/$slug': typeof HerramientasIaSlugRoute
  '/mapa/$slug': typeof MapaSlugRoute
  '/membresia/cancelado': typeof MembresiaCanceladoRoute
  '/membresia/exito': typeof MembresiaExitoRoute
  '/paises/$country': typeof PaisesCountryRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/respuestas-familia/$slug': typeof RespuestasFamiliaSlugRoute
  '/apoyo-familiar/': typeof ApoyoFamiliarIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/coaching-pago/': typeof CoachingPagoIndexRoute
  '/herramientas-ia/': typeof HerramientasIaIndexRoute
  '/mapa/': typeof MapaIndexRoute
  '/membresia/': typeof MembresiaIndexRoute
  '/paises/': typeof PaisesIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/respuestas-familia/': typeof RespuestasFamiliaIndexRoute
  '/api/zoom/automation': typeof ApiZoomAutomationRoute
  '/api/zoom/register': typeof ApiZoomRegisterRoute
  '/api/zoom/schedule': typeof ApiZoomScheduleRoute
  '/api/zoom/webhook': typeof ApiZoomWebhookRoute
  '/apoyo-familiar/$state/$city': typeof ApoyoFamiliarStateCityRoute
  '/apoyo-familiar/$state/': typeof ApoyoFamiliarStateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/circulo-familiar': typeof CirculoFamiliarRoute
  '/coaching-familiar': typeof CoachingFamiliarRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/faq': typeof FaqRoute
  '/grabaciones': typeof GrabacionesRoute
  '/ingresar': typeof IngresarRoute
  '/intervencion': typeof IntervencionRoute
  '/privacidad': typeof PrivacidadRoute
  '/proveedores': typeof ProveedoresRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/terminos-sms': typeof TerminosSmsRoute
  '/testimonios': typeof TestimoniosRoute
  '/api/registro': typeof ApiRegistroRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coaching-pago/exito': typeof CoachingPagoExitoRoute
  '/herramientas-ia/$slug': typeof HerramientasIaSlugRoute
  '/mapa/$slug': typeof MapaSlugRoute
  '/membresia/cancelado': typeof MembresiaCanceladoRoute
  '/membresia/exito': typeof MembresiaExitoRoute
  '/paises/$country': typeof PaisesCountryRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/respuestas-familia/$slug': typeof RespuestasFamiliaSlugRoute
  '/apoyo-familiar': typeof ApoyoFamiliarIndexRoute
  '/blog': typeof BlogIndexRoute
  '/coaching-pago': typeof CoachingPagoIndexRoute
  '/herramientas-ia': typeof HerramientasIaIndexRoute
  '/mapa': typeof MapaIndexRoute
  '/membresia': typeof MembresiaIndexRoute
  '/paises': typeof PaisesIndexRoute
  '/recursos': typeof RecursosIndexRoute
  '/respuestas-familia': typeof RespuestasFamiliaIndexRoute
  '/api/zoom/automation': typeof ApiZoomAutomationRoute
  '/api/zoom/register': typeof ApiZoomRegisterRoute
  '/api/zoom/schedule': typeof ApiZoomScheduleRoute
  '/api/zoom/webhook': typeof ApiZoomWebhookRoute
  '/apoyo-familiar/$state/$city': typeof ApoyoFamiliarStateCityRoute
  '/apoyo-familiar/$state': typeof ApoyoFamiliarStateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apoyo-familiar': typeof ApoyoFamiliarRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/circulo-familiar': typeof CirculoFamiliarRoute
  '/coaching-familiar': typeof CoachingFamiliarRoute
  '/coaching-pago': typeof CoachingPagoRouteWithChildren
  '/evaluaciones': typeof EvaluacionesRoute
  '/faq': typeof FaqRoute
  '/grabaciones': typeof GrabacionesRoute
  '/herramientas-ia': typeof HerramientasIaRouteWithChildren
  '/ingresar': typeof IngresarRoute
  '/intervencion': typeof IntervencionRoute
  '/mapa': typeof MapaRouteWithChildren
  '/membresia': typeof MembresiaRouteWithChildren
  '/paises': typeof PaisesRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/proveedores': typeof ProveedoresRoute
  '/recursos': typeof RecursosRouteWithChildren
  '/registro': typeof RegistroRoute
  '/respuestas-familia': typeof RespuestasFamiliaRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/terminos-sms': typeof TerminosSmsRoute
  '/testimonios': typeof TestimoniosRoute
  '/api/registro': typeof ApiRegistroRoute
  '/apoyo-familiar/$state': typeof ApoyoFamiliarStateRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/coaching-pago/exito': typeof CoachingPagoExitoRoute
  '/herramientas-ia/$slug': typeof HerramientasIaSlugRoute
  '/mapa/$slug': typeof MapaSlugRoute
  '/membresia/cancelado': typeof MembresiaCanceladoRoute
  '/membresia/exito': typeof MembresiaExitoRoute
  '/paises/$country': typeof PaisesCountryRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/respuestas-familia/$slug': typeof RespuestasFamiliaSlugRoute
  '/apoyo-familiar/': typeof ApoyoFamiliarIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/coaching-pago/': typeof CoachingPagoIndexRoute
  '/herramientas-ia/': typeof HerramientasIaIndexRoute
  '/mapa/': typeof MapaIndexRoute
  '/membresia/': typeof MembresiaIndexRoute
  '/paises/': typeof PaisesIndexRoute
  '/recursos/': typeof RecursosIndexRoute
  '/respuestas-familia/': typeof RespuestasFamiliaIndexRoute
  '/api/zoom/automation': typeof ApiZoomAutomationRoute
  '/api/zoom/register': typeof ApiZoomRegisterRoute
  '/api/zoom/schedule': typeof ApiZoomScheduleRoute
  '/api/zoom/webhook': typeof ApiZoomWebhookRoute
  '/apoyo-familiar/$state/$city': typeof ApoyoFamiliarStateCityRoute
  '/apoyo-familiar/$state/': typeof ApoyoFamiliarStateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apoyo-familiar'
    | '/auth'
    | '/blog'
    | '/circulo-familiar'
    | '/coaching-familiar'
    | '/coaching-pago'
    | '/evaluaciones'
    | '/faq'
    | '/grabaciones'
    | '/herramientas-ia'
    | '/ingresar'
    | '/intervencion'
    | '/mapa'
    | '/membresia'
    | '/paises'
    | '/privacidad'
    | '/proveedores'
    | '/recursos'
    | '/registro'
    | '/respuestas-familia'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/terminos'
    | '/terminos-sms'
    | '/testimonios'
    | '/api/registro'
    | '/apoyo-familiar/$state'
    | '/blog/$slug'
    | '/coaching-pago/exito'
    | '/herramientas-ia/$slug'
    | '/mapa/$slug'
    | '/membresia/cancelado'
    | '/membresia/exito'
    | '/paises/$country'
    | '/recursos/$slug'
    | '/respuestas-familia/$slug'
    | '/apoyo-familiar/'
    | '/blog/'
    | '/coaching-pago/'
    | '/herramientas-ia/'
    | '/mapa/'
    | '/membresia/'
    | '/paises/'
    | '/recursos/'
    | '/respuestas-familia/'
    | '/api/zoom/automation'
    | '/api/zoom/register'
    | '/api/zoom/schedule'
    | '/api/zoom/webhook'
    | '/apoyo-familiar/$state/$city'
    | '/apoyo-familiar/$state/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/circulo-familiar'
    | '/coaching-familiar'
    | '/evaluaciones'
    | '/faq'
    | '/grabaciones'
    | '/ingresar'
    | '/intervencion'
    | '/privacidad'
    | '/proveedores'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/terminos'
    | '/terminos-sms'
    | '/testimonios'
    | '/api/registro'
    | '/blog/$slug'
    | '/coaching-pago/exito'
    | '/herramientas-ia/$slug'
    | '/mapa/$slug'
    | '/membresia/cancelado'
    | '/membresia/exito'
    | '/paises/$country'
    | '/recursos/$slug'
    | '/respuestas-familia/$slug'
    | '/apoyo-familiar'
    | '/blog'
    | '/coaching-pago'
    | '/herramientas-ia'
    | '/mapa'
    | '/membresia'
    | '/paises'
    | '/recursos'
    | '/respuestas-familia'
    | '/api/zoom/automation'
    | '/api/zoom/register'
    | '/api/zoom/schedule'
    | '/api/zoom/webhook'
    | '/apoyo-familiar/$state/$city'
    | '/apoyo-familiar/$state'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apoyo-familiar'
    | '/auth'
    | '/blog'
    | '/circulo-familiar'
    | '/coaching-familiar'
    | '/coaching-pago'
    | '/evaluaciones'
    | '/faq'
    | '/grabaciones'
    | '/herramientas-ia'
    | '/ingresar'
    | '/intervencion'
    | '/mapa'
    | '/membresia'
    | '/paises'
    | '/privacidad'
    | '/proveedores'
    | '/recursos'
    | '/registro'
    | '/respuestas-familia'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/terminos'
    | '/terminos-sms'
    | '/testimonios'
    | '/api/registro'
    | '/apoyo-familiar/$state'
    | '/blog/$slug'
    | '/coaching-pago/exito'
    | '/herramientas-ia/$slug'
    | '/mapa/$slug'
    | '/membresia/cancelado'
    | '/membresia/exito'
    | '/paises/$country'
    | '/recursos/$slug'
    | '/respuestas-familia/$slug'
    | '/apoyo-familiar/'
    | '/blog/'
    | '/coaching-pago/'
    | '/herramientas-ia/'
    | '/mapa/'
    | '/membresia/'
    | '/paises/'
    | '/recursos/'
    | '/respuestas-familia/'
    | '/api/zoom/automation'
    | '/api/zoom/register'
    | '/api/zoom/schedule'
    | '/api/zoom/webhook'
    | '/apoyo-familiar/$state/$city'
    | '/apoyo-familiar/$state/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApoyoFamiliarRoute: typeof ApoyoFamiliarRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CirculoFamiliarRoute: typeof CirculoFamiliarRoute
  CoachingFamiliarRoute: typeof CoachingFamiliarRoute
  CoachingPagoRoute: typeof CoachingPagoRouteWithChildren
  EvaluacionesRoute: typeof EvaluacionesRoute
  FaqRoute: typeof FaqRoute
  GrabacionesRoute: typeof GrabacionesRoute
  HerramientasIaRoute: typeof HerramientasIaRouteWithChildren
  IngresarRoute: typeof IngresarRoute
  IntervencionRoute: typeof IntervencionRoute
  MapaRoute: typeof MapaRouteWithChildren
  MembresiaRoute: typeof MembresiaRouteWithChildren
  PaisesRoute: typeof PaisesRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  ProveedoresRoute: typeof ProveedoresRoute
  RecursosRoute: typeof RecursosRouteWithChildren
  RegistroRoute: typeof RegistroRoute
  RespuestasFamiliaRoute: typeof RespuestasFamiliaRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TerminosRoute: typeof TerminosRoute
  TerminosSmsRoute: typeof TerminosSmsRoute
  TestimoniosRoute: typeof TestimoniosRoute
  ApiRegistroRoute: typeof ApiRegistroRoute
  ApiZoomAutomationRoute: typeof ApiZoomAutomationRoute
  ApiZoomRegisterRoute: typeof ApiZoomRegisterRoute
  ApiZoomScheduleRoute: typeof ApiZoomScheduleRoute
  ApiZoomWebhookRoute: typeof ApiZoomWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-sms': {
      id: '/terminos-sms'
      path: '/terminos-sms'
      fullPath: '/terminos-sms'
      preLoaderRoute: typeof TerminosSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respuestas-familia': {
      id: '/respuestas-familia'
      path: '/respuestas-familia'
      fullPath: '/respuestas-familia'
      preLoaderRoute: typeof RespuestasFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paises': {
      id: '/paises'
      path: '/paises'
      fullPath: '/paises'
      preLoaderRoute: typeof PaisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membresia': {
      id: '/membresia'
      path: '/membresia'
      fullPath: '/membresia'
      preLoaderRoute: typeof MembresiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervencion': {
      id: '/intervencion'
      path: '/intervencion'
      fullPath: '/intervencion'
      preLoaderRoute: typeof IntervencionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas-ia': {
      id: '/herramientas-ia'
      path: '/herramientas-ia'
      fullPath: '/herramientas-ia'
      preLoaderRoute: typeof HerramientasIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grabaciones': {
      id: '/grabaciones'
      path: '/grabaciones'
      fullPath: '/grabaciones'
      preLoaderRoute: typeof GrabacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones': {
      id: '/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/evaluaciones'
      preLoaderRoute: typeof EvaluacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching-pago': {
      id: '/coaching-pago'
      path: '/coaching-pago'
      fullPath: '/coaching-pago'
      preLoaderRoute: typeof CoachingPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching-familiar': {
      id: '/coaching-familiar'
      path: '/coaching-familiar'
      fullPath: '/coaching-familiar'
      preLoaderRoute: typeof CoachingFamiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulo-familiar': {
      id: '/circulo-familiar'
      path: '/circulo-familiar'
      fullPath: '/circulo-familiar'
      preLoaderRoute: typeof CirculoFamiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo-familiar': {
      id: '/apoyo-familiar'
      path: '/apoyo-familiar'
      fullPath: '/apoyo-familiar'
      preLoaderRoute: typeof ApoyoFamiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respuestas-familia/': {
      id: '/respuestas-familia/'
      path: '/'
      fullPath: '/respuestas-familia/'
      preLoaderRoute: typeof RespuestasFamiliaIndexRouteImport
      parentRoute: typeof RespuestasFamiliaRoute
    }
    '/recursos/': {
      id: '/recursos/'
      path: '/'
      fullPath: '/recursos/'
      preLoaderRoute: typeof RecursosIndexRouteImport
      parentRoute: typeof RecursosRoute
    }
    '/paises/': {
      id: '/paises/'
      path: '/'
      fullPath: '/paises/'
      preLoaderRoute: typeof PaisesIndexRouteImport
      parentRoute: typeof PaisesRoute
    }
    '/membresia/': {
      id: '/membresia/'
      path: '/'
      fullPath: '/membresia/'
      preLoaderRoute: typeof MembresiaIndexRouteImport
      parentRoute: typeof MembresiaRoute
    }
    '/mapa/': {
      id: '/mapa/'
      path: '/'
      fullPath: '/mapa/'
      preLoaderRoute: typeof MapaIndexRouteImport
      parentRoute: typeof MapaRoute
    }
    '/herramientas-ia/': {
      id: '/herramientas-ia/'
      path: '/'
      fullPath: '/herramientas-ia/'
      preLoaderRoute: typeof HerramientasIaIndexRouteImport
      parentRoute: typeof HerramientasIaRoute
    }
    '/coaching-pago/': {
      id: '/coaching-pago/'
      path: '/'
      fullPath: '/coaching-pago/'
      preLoaderRoute: typeof CoachingPagoIndexRouteImport
      parentRoute: typeof CoachingPagoRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/apoyo-familiar/': {
      id: '/apoyo-familiar/'
      path: '/'
      fullPath: '/apoyo-familiar/'
      preLoaderRoute: typeof ApoyoFamiliarIndexRouteImport
      parentRoute: typeof ApoyoFamiliarRoute
    }
    '/respuestas-familia/$slug': {
      id: '/respuestas-familia/$slug'
      path: '/$slug'
      fullPath: '/respuestas-familia/$slug'
      preLoaderRoute: typeof RespuestasFamiliaSlugRouteImport
      parentRoute: typeof RespuestasFamiliaRoute
    }
    '/recursos/$slug': {
      id: '/recursos/$slug'
      path: '/$slug'
      fullPath: '/recursos/$slug'
      preLoaderRoute: typeof RecursosSlugRouteImport
      parentRoute: typeof RecursosRoute
    }
    '/paises/$country': {
      id: '/paises/$country'
      path: '/$country'
      fullPath: '/paises/$country'
      preLoaderRoute: typeof PaisesCountryRouteImport
      parentRoute: typeof PaisesRoute
    }
    '/membresia/exito': {
      id: '/membresia/exito'
      path: '/exito'
      fullPath: '/membresia/exito'
      preLoaderRoute: typeof MembresiaExitoRouteImport
      parentRoute: typeof MembresiaRoute
    }
    '/membresia/cancelado': {
      id: '/membresia/cancelado'
      path: '/cancelado'
      fullPath: '/membresia/cancelado'
      preLoaderRoute: typeof MembresiaCanceladoRouteImport
      parentRoute: typeof MembresiaRoute
    }
    '/mapa/$slug': {
      id: '/mapa/$slug'
      path: '/$slug'
      fullPath: '/mapa/$slug'
      preLoaderRoute: typeof MapaSlugRouteImport
      parentRoute: typeof MapaRoute
    }
    '/herramientas-ia/$slug': {
      id: '/herramientas-ia/$slug'
      path: '/$slug'
      fullPath: '/herramientas-ia/$slug'
      preLoaderRoute: typeof HerramientasIaSlugRouteImport
      parentRoute: typeof HerramientasIaRoute
    }
    '/coaching-pago/exito': {
      id: '/coaching-pago/exito'
      path: '/exito'
      fullPath: '/coaching-pago/exito'
      preLoaderRoute: typeof CoachingPagoExitoRouteImport
      parentRoute: typeof CoachingPagoRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/apoyo-familiar/$state': {
      id: '/apoyo-familiar/$state'
      path: '/$state'
      fullPath: '/apoyo-familiar/$state'
      preLoaderRoute: typeof ApoyoFamiliarStateRouteImport
      parentRoute: typeof ApoyoFamiliarRoute
    }
    '/api/registro': {
      id: '/api/registro'
      path: '/api/registro'
      fullPath: '/api/registro'
      preLoaderRoute: typeof ApiRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo-familiar/$state/': {
      id: '/apoyo-familiar/$state/'
      path: '/'
      fullPath: '/apoyo-familiar/$state/'
      preLoaderRoute: typeof ApoyoFamiliarStateIndexRouteImport
      parentRoute: typeof ApoyoFamiliarStateRoute
    }
    '/apoyo-familiar/$state/$city': {
      id: '/apoyo-familiar/$state/$city'
      path: '/$city'
      fullPath: '/apoyo-familiar/$state/$city'
      preLoaderRoute: typeof ApoyoFamiliarStateCityRouteImport
      parentRoute: typeof ApoyoFamiliarStateRoute
    }
    '/api/zoom/webhook': {
      id: '/api/zoom/webhook'
      path: '/api/zoom/webhook'
      fullPath: '/api/zoom/webhook'
      preLoaderRoute: typeof ApiZoomWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zoom/schedule': {
      id: '/api/zoom/schedule'
      path: '/api/zoom/schedule'
      fullPath: '/api/zoom/schedule'
      preLoaderRoute: typeof ApiZoomScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zoom/register': {
      id: '/api/zoom/register'
      path: '/api/zoom/register'
      fullPath: '/api/zoom/register'
      preLoaderRoute: typeof ApiZoomRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zoom/automation': {
      id: '/api/zoom/automation'
      path: '/api/zoom/automation'
      fullPath: '/api/zoom/automation'
      preLoaderRoute: typeof ApiZoomAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApoyoFamiliarStateRouteChildren {
  ApoyoFamiliarStateCityRoute: typeof ApoyoFamiliarStateCityRoute
  ApoyoFamiliarStateIndexRoute: typeof ApoyoFamiliarStateIndexRoute
}

const ApoyoFamiliarStateRouteChildren: ApoyoFamiliarStateRouteChildren = {
  ApoyoFamiliarStateCityRoute: ApoyoFamiliarStateCityRoute,
  ApoyoFamiliarStateIndexRoute: ApoyoFamiliarStateIndexRoute,
}

const ApoyoFamiliarStateRouteWithChildren =
  ApoyoFamiliarStateRoute._addFileChildren(ApoyoFamiliarStateRouteChildren)

interface ApoyoFamiliarRouteChildren {
  ApoyoFamiliarStateRoute: typeof ApoyoFamiliarStateRouteWithChildren
  ApoyoFamiliarIndexRoute: typeof ApoyoFamiliarIndexRoute
}

const ApoyoFamiliarRouteChildren: ApoyoFamiliarRouteChildren = {
  ApoyoFamiliarStateRoute: ApoyoFamiliarStateRouteWithChildren,
  ApoyoFamiliarIndexRoute: ApoyoFamiliarIndexRoute,
}

const ApoyoFamiliarRouteWithChildren = ApoyoFamiliarRoute._addFileChildren(
  ApoyoFamiliarRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CoachingPagoRouteChildren {
  CoachingPagoExitoRoute: typeof CoachingPagoExitoRoute
  CoachingPagoIndexRoute: typeof CoachingPagoIndexRoute
}

const CoachingPagoRouteChildren: CoachingPagoRouteChildren = {
  CoachingPagoExitoRoute: CoachingPagoExitoRoute,
  CoachingPagoIndexRoute: CoachingPagoIndexRoute,
}

const CoachingPagoRouteWithChildren = CoachingPagoRoute._addFileChildren(
  CoachingPagoRouteChildren,
)

interface HerramientasIaRouteChildren {
  HerramientasIaSlugRoute: typeof HerramientasIaSlugRoute
  HerramientasIaIndexRoute: typeof HerramientasIaIndexRoute
}

const HerramientasIaRouteChildren: HerramientasIaRouteChildren = {
  HerramientasIaSlugRoute: HerramientasIaSlugRoute,
  HerramientasIaIndexRoute: HerramientasIaIndexRoute,
}

const HerramientasIaRouteWithChildren = HerramientasIaRoute._addFileChildren(
  HerramientasIaRouteChildren,
)

interface MapaRouteChildren {
  MapaSlugRoute: typeof MapaSlugRoute
  MapaIndexRoute: typeof MapaIndexRoute
}

const MapaRouteChildren: MapaRouteChildren = {
  MapaSlugRoute: MapaSlugRoute,
  MapaIndexRoute: MapaIndexRoute,
}

const MapaRouteWithChildren = MapaRoute._addFileChildren(MapaRouteChildren)

interface MembresiaRouteChildren {
  MembresiaCanceladoRoute: typeof MembresiaCanceladoRoute
  MembresiaExitoRoute: typeof MembresiaExitoRoute
  MembresiaIndexRoute: typeof MembresiaIndexRoute
}

const MembresiaRouteChildren: MembresiaRouteChildren = {
  MembresiaCanceladoRoute: MembresiaCanceladoRoute,
  MembresiaExitoRoute: MembresiaExitoRoute,
  MembresiaIndexRoute: MembresiaIndexRoute,
}

const MembresiaRouteWithChildren = MembresiaRoute._addFileChildren(
  MembresiaRouteChildren,
)

interface PaisesRouteChildren {
  PaisesCountryRoute: typeof PaisesCountryRoute
  PaisesIndexRoute: typeof PaisesIndexRoute
}

const PaisesRouteChildren: PaisesRouteChildren = {
  PaisesCountryRoute: PaisesCountryRoute,
  PaisesIndexRoute: PaisesIndexRoute,
}

const PaisesRouteWithChildren =
  PaisesRoute._addFileChildren(PaisesRouteChildren)

interface RecursosRouteChildren {
  RecursosSlugRoute: typeof RecursosSlugRoute
  RecursosIndexRoute: typeof RecursosIndexRoute
}

const RecursosRouteChildren: RecursosRouteChildren = {
  RecursosSlugRoute: RecursosSlugRoute,
  RecursosIndexRoute: RecursosIndexRoute,
}

const RecursosRouteWithChildren = RecursosRoute._addFileChildren(
  RecursosRouteChildren,
)

interface RespuestasFamiliaRouteChildren {
  RespuestasFamiliaSlugRoute: typeof RespuestasFamiliaSlugRoute
  RespuestasFamiliaIndexRoute: typeof RespuestasFamiliaIndexRoute
}

const RespuestasFamiliaRouteChildren: RespuestasFamiliaRouteChildren = {
  RespuestasFamiliaSlugRoute: RespuestasFamiliaSlugRoute,
  RespuestasFamiliaIndexRoute: RespuestasFamiliaIndexRoute,
}

const RespuestasFamiliaRouteWithChildren =
  RespuestasFamiliaRoute._addFileChildren(RespuestasFamiliaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApoyoFamiliarRoute: ApoyoFamiliarRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CirculoFamiliarRoute: CirculoFamiliarRoute,
  CoachingFamiliarRoute: CoachingFamiliarRoute,
  CoachingPagoRoute: CoachingPagoRouteWithChildren,
  EvaluacionesRoute: EvaluacionesRoute,
  FaqRoute: FaqRoute,
  GrabacionesRoute: GrabacionesRoute,
  HerramientasIaRoute: HerramientasIaRouteWithChildren,
  IngresarRoute: IngresarRoute,
  IntervencionRoute: IntervencionRoute,
  MapaRoute: MapaRouteWithChildren,
  MembresiaRoute: MembresiaRouteWithChildren,
  PaisesRoute: PaisesRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  ProveedoresRoute: ProveedoresRoute,
  RecursosRoute: RecursosRouteWithChildren,
  RegistroRoute: RegistroRoute,
  RespuestasFamiliaRoute: RespuestasFamiliaRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TerminosRoute: TerminosRoute,
  TerminosSmsRoute: TerminosSmsRoute,
  TestimoniosRoute: TestimoniosRoute,
  ApiRegistroRoute: ApiRegistroRoute,
  ApiZoomAutomationRoute: ApiZoomAutomationRoute,
  ApiZoomRegisterRoute: ApiZoomRegisterRoute,
  ApiZoomScheduleRoute: ApiZoomScheduleRoute,
  ApiZoomWebhookRoute: ApiZoomWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
